language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install nose unittest2 mock --use-mirrors
    - pip install . --use-mirrors
    - pip install Markdown
script: nosetests -s pelican
notifications:
    irc:
        channels: 
            - "irc.freenode.org#pelican"
        on_success: change
